default:
  target: dev
  outputs:

    dev:
      type: snowflake
      account: "<your_account>"         
      user: "<your_username>"
      password: "<your_password>"
      role: "DEVELOPER"
      database: "DEV_DB"
      warehouse: "DEV_WH"
      schema: "ANALYTICS_DEV"
      threads: 4
      client_session_keep_alive: false

    prod:
      type: snowflake
      account: "<your_account>"
      user: "<your_username>"
      password: "<your_password>"
      role: "TRANSFORMER"              
      database: "PROD_DB"              
      warehouse: "PROD_WH"             
      schema: "ANALYTICS"              
      threads: 4
      client_session_keep_alive: false
